/**
 *
 * @author Andriopoulos Xristos
 * @author Karagiannis Ioannis
 * @author Demisarlis Thomas
 */
package view;

import java.awt.Image;
import javax.swing.ImageIcon;

/**
 * Αρχική φόρμα της εφαρμογής.
 * Μέσα από την αρχική φόρμα ανοίγουν οι υπόλοιπες φόρμες.
 */
public class MainForm extends javax.swing.JFrame {

    // Μέσα από την αρχική φόρμα ανοίγουν οι υπόλοιπες φόρμες
    private final SearchForm searchForm;
    private final StoredArticlesForm storedArticlesForm;
    private final StatisticsForm statisticsForm;

    /**
     * Δημιουργεί και επιστρέφει ένα εικονίδιο με τις επιθυμητές διαστάσεις.
     * 
     * @param path Η διαδρομή του εικονιδίου.
     * @param w    Το πλάτος του εικονιδίου.
     * @param h    Το ύψος του εικονιδίου.
     * @return Το εικονίδιο με τις νέες διαστάσεις.
     */
    private ImageIcon scaledIcon(String path, int w, int h) {
        Image img = new ImageIcon(MainForm.class.getResource(path)).getImage();
        Image scaled = img.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new ImageIcon(scaled);
    }

    /**
     * Constructor της αρχικής φόρμας.
     */
    public MainForm() {
        initComponents();

        // Βάζω τo εικονίδιο της Φόρμας, ομοίως για όλες τις φόρμες
        Image pageIcon = new ImageIcon(MainForm.class.getResource("/resources/wikilogo.png")).getImage();
        setIconImage(pageIcon);
        // Αρχικοποίηση στοιχείων φόρμας

        jLabel1.setText(
                "<html><center><h2>Καλώς ήρθατε στην εφαρμογή μας</h2><br><h3>Ανδριόπουλος Χρήστος<br>Καραγιάννης Ιωάννης<br>Θωμάς Δεμισαρλής</h3></center></html>");
        jButton1.setText("Αναζήτηση");
        jButton1.setIcon(scaledIcon("/resources/search.png", 16, 16));
        jButton2.setText("Αποθηκευμένα άρθρα");
        jButton2.setIcon(scaledIcon("/resources/book-alt.png", 16, 16));
        jButton3.setText("Προβολή στατιστικών");
        jButton3.setIcon(scaledIcon("/resources/chart-histogram.png", 16, 16));
        jButton4.setText("Προσθήκη νέου άρθρου σε κατηγορία (Χειροκίνητη εισαγωγή)");
        jButton4.setIcon(scaledIcon("/resources/convert-shapes.png", 16, 16));
        jButton5.setText("Τροποποίηση άρθρων σε κατηγορία");
        jButton5.setIcon(scaledIcon("/resources/edit.png", 16, 16));
        jButton6.setText("Προσθήκη κατηγορίας");
        jButton6.setIcon(scaledIcon("/resources/add.png", 16, 16));

        jButton7.setText("Έξοδος");
        jButton7.setIcon(scaledIcon("/resources/exit-alt.png", 16, 16));

        // Τίτλος φόρμας
        setTitle("Αρχική Οθόνη");
        // Κεντράρισμα της φόρμας
        setLocationRelativeTo(null);
        // Η φόρμα δεν μπορεί να αλλάξει μέγεθος
        setResizable(false);

        pack();
        setLocationRelativeTo(null);

        // Δημιουργία των άλλων φορμών
        searchForm = new SearchForm();
        statisticsForm = new StatisticsForm();
        storedArticlesForm = new StoredArticlesForm();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("jLabel1");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel1.setAlignmentY(0.0F);
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton7.setText("jButton7");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton4.setText("jButton4");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("jButton5");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(235, 235, 235)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 400,
                                                Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 400,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(224, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL,
                new java.awt.Component[] { jButton1, jButton2, jButton3 });

        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(jLabel1)
                                .addGap(75, 75, 75)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton7)
                                .addGap(52, 52, 52)));

        layout.linkSize(javax.swing.SwingConstants.VERTICAL,
                new java.awt.Component[] { jButton1, jButton2, jButton3, jButton4, jButton5, jButton6, jButton7 });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Άνοιγμα της φόρμας αναζήτησης άρθρων
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        searchForm.setVisible(true);
    }// GEN-LAST:event_jButton1ActionPerformed

    // Άνοιγμα της φόρμας αποθηκευμένων άρθρων
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        storedArticlesForm.updateArticles();
        storedArticlesForm.setVisible(true);
    }// GEN-LAST:event_jButton2ActionPerformed

    // Άνοιγμα της φόρμας στατιστικών
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton3ActionPerformed
        this.dispose();
        statisticsForm.getCategoriesData();
        statisticsForm.getSearchesData();
        statisticsForm.setVisible(true);
    }// GEN-LAST:event_jButton3ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }// GEN-LAST:event_jButton7ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton4ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, " Για την ώρα δεν είναι διαθέσιμο ");
    }// GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton5ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, " Για την ώρα δεν είναι διαθέσιμο ");
    }// GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jButton6ActionPerformed
        javax.swing.JOptionPane.showMessageDialog(this, " Για την ώρα δεν είναι διαθέσιμο ");
    }// GEN-LAST:event_jButton6ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
